"""add issue table

Revision ID: cf0c5e501c2a
Revises: f9fa58551711
Create Date: 2026-02-02 00:58:37.752927

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cf0c5e501c2a"
down_revision: Union[str, Sequence[str], None] = "f9fa58551711"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
