"""add verification codes

Revision ID: fc7119408f56
Revises: b4fdcabfa500
Create Date: 2026-02-03 00:27:47.728066

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fc7119408f56"
down_revision: Union[str, Sequence[str], None] = "b4fdcabfa500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
